name: petrov_hockey_academy_flutter
description: Flutter app of the Petrov Hockey Academy led by Sportsoft.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  date_picker_timeline: ^1.2.3
  equatable: ^2.0.3
  firebase_core_platform_interface: 4.5.3
  firebase_messaging: ^14.2.6
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.0
  google_fonts: ^3.0.1
  url_launcher: ^6.1.7
  mask_text_input_formatter: ^2.4.0
  image_picker: ^0.8.5+3
  badges: ^3.0.2
  flutter_local_notifications: ^9.9.1
  graphql_flutter: ^5.1.0
  wechat_assets_picker: ^8.1.3
  # json_annotation: ^4.8.0
  get_it: ^7.2.0
  shimmer: ^2.0.0
  connectivity_plus: ^3.0.4

dev_dependencies:
  flutter_launcher_icons: ^0.12.0  
  flutter_native_splash: ^2.2.19
  # json_serializable: ^6.6.1 
  # build_runner: ^2.0.5


flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons: 
  android: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  image: assets/logo.png
  color: "#172439"
  fullscreen: true
  android_12:
    image: assets/logo.png
    icon_background_color: "#172439"
    fullscreen: true


dependency_overrides:
  bloc: ^8.1.0
  flutter_bloc: ^8.0.1
  dependency_validator: ^3.0.0

